module.exports = {
  PAYLOAD_KEY: 'payload',
  MEDIA_IMAGE_KEY: 'mediaImage',
  ADMIN_TOKEN_STATUS_CODES: { REVOKED: 'REVOKED', ACTIVE: 'ACTIVE' },
  ROLES: { USER: 'USER', ADMIN: 'ADMIN', SUPER_ADMIN: 'SUPER_ADMIN' },
};
