module.exports = {
  PARTY_IMAGE_KEY: 'partyImage',
  CONTESTANT_IMAGE_KEY: 'contestantImage',
  ADMIN_TOKEN_STATUSES: { REVOKED: 'REVOKED', ACTIVE: 'ACTIVE' },
  ROLES: { USER: 'USER', ADMIN: 'ADMIN', SUPER_ADMIN: 'SUPER_ADMIN' },
};
