module.exports = {
  USER_IMAGE_KEY: 'image',
  ADMIN_TOKEN_STATUSES: { REVOKED: 'REVOKED', ACTIVE: 'ACTIVE' },
  ROLES: { USER: 'USER', ADMIN: 'ADMIN', SUPER_ADMIN: 'SUPER_ADMIN' },
  ERROR_CODES: {
    SESSION_EXPIRED: 'E001',
    REFRESH_TOKEN_EXPIRED: 'E002',
    MISSING_TOKEN: 'E003',
    MISSING_REFRESH_TOKEN: 'E004',
  },
};
